server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location /products {
        proxy_pass http://category-product-service:5001;
        proxy_set_header Host $host;
    }
    location /categories {
        proxy_pass http://category-product-service:5001;
        proxy_set_header Host $host;
    }
    location /makeline {
        proxy_pass http://makeline-service:5002;
        proxy_set_header Host $host;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
